apiVersion: batch/v1 # Jobs Default K8 API
kind: Job # This tells kubernetes what kind of class it is working with
metadata:
  name: resnet-benchmark-job # Name of the Job
spec:
  completions: 100
  parallelism: 25
  template: # Pod Templete
    spec:
      restartPolicy: OnFailure # Options are Always, OnFailure, and Never.
      hostNetwork: true # This option will allow the pod to use the host network for internet access
      containers:
      - name: kubernetes-ml-example # Container name (Can be set to whatever)
        image: synicix/kubernetes_ml_example_docker:latest # Docker Image hosted on Docker Hub
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPUs
        env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        command: ["/bin/sh"]
        args: ["-c", "python3 KubernetesMLExample/resnet_benchmark/resnet_benchmark.py"] # sh commands to clone and run python script
